baseURL: 'https://fajarr.space/'
languageCode: en-us
title: fajarspace
googleAnalytics: UA-PROPERTY_ID
permalinks:
  tulisan: /:slug/
  rekomendasi: /:slug/
disqusShortname: fajars-space
tags: []
Params:
  description: Temukan Tulisan / baca blog Tech
  images:
    - /digital-garden-logo.png
  enableSearch: true
  newsletter:
    title: ''
    description: A curated weekly digest once a week to your mailbox
    provider: buttondown
    path: 'https://buttondown.email/api/emails/embed-subscribe/'
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Content
      params:
        header: true
      weight: 2
    - name: Tulisan
      url: /tulisan
      weight: 3
    - name: Blog Tech
      url: /tech
      weight: 4
    - name: Portfolio
      url: 'https://fajarr.netlify.app/'
      weight: 4
    - name: Stack
      url: /stack
      weight: 5
    - name: Links
      params:
        header: true
      weight: 6
    - name: Stuff CSS
      url: 'https://stuffcss.netlify.app'
      weight: 7
  social:
    - name: Twitter
      url: 'https://twitter.com/fajaragngn'
      weight: 1
    - name: GitHub
      url: 'https://github.com/fajarspace'
      weight: 2
    - name: LinkedIn
      url: 'https://linkedin.com'
      weight: 3
    - name: Instagram
      url: 'https://instagram.com/fajar.agngn'
      weight: 4
    - name: Dribbble
      url: 'https://dribbble.com'
      weight: 5
    - name: Codepen
      url: 'https://codepen.io'
      weight: 6
    - name: Twitch
      url: 'https://twitch.com'
      weight: 7
    - name: Email
      url: 'mailto:fajar.agngn@gmail.com'
      weight: 8
    - name: RSS
      url: /tulisan/index.xml
      weight: 9
markup:
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
