baseURL: https://fajarspace.netlify.app/
languageCode: id
title: Fajar Agung

params:
  description: Temukan Tulisan / baca blog dev, kamu juga bisa mendengarkan Podcast
staticDir: static

disqusShortname: fajars-space

tags: []

permalinks:
  blog: /:slug/
  rekomendasi: /:slug/

outputs:
  home: ["HTML", "RSS", "JSON"]
