---
label: Project
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: text
  name: title
  label: title
pages:
- content/project/selembarkertas-podcast.md
